export const SITE_META = {
  name: `SuperEasyGame`,
  url: `https://www.supereasygame.com/`,
  domain: `supereasygame.com`,
};

export const API_URL = `https://uptapapi.uptap.com/h5Game/?type=GameList&platform=uptapgame0120&token=dXB0YXBnYW1l572R56uZ55So`;
export const GAME_PATH = `https://uptapapi.uptap.com/h5Game/?type=Game&platform=youletech&appid=`;

export const ADS_ID = `ca-pub-9209477879340784`;
export const GA_ID = `G-DDF82DXW7Z`;

// 广告ID
export const ADS_SLOT_ID = {
  home: `8841942463`,
  category: `2623469732`,
  detail: `7528860791`,
};
export const EXCLUDED_GAMES = [];
export const SELECTED_GAMES = [
  "BigSword",
  "BoardTheTrain",
  "FireTheGun",
  "MergeGuns3D",
  "FeverRacing",
  "ColorBall3D",
  "ZombieSurvival",
  "CrazyMoto",
  "LetMeIn",
  "BumbleShooter",
  "Knife",
  "HiTaxi",
  "TrafficRun",
  "BulletMaster3D",
  "MrRacer",
  "MagicParkour",
  "FrozenMagic",
  "MrBullet",
  "JumpSmash",
  "CrazyKnife",
  "TrafficPassing",
  "SuperThrow",
  "AceMan",
  "BatterKing",
  "KnockBalls",
  "CrashTower3D",
  "DragonCrush",
  "SnakeGo",
  "CrackShot",
  "BallIsComing",
  "BounceShooter",
  "HillRacing",
  "BlockGun3D",
  "FruitMonster",
  "FierceCity",
  "CrazyDrift",
  "FruitsFall",
  "MagicPaint",
  "MergeKill",
  "CrazyHammer",
  "FingerCannon",
  "BulletMan",
  "GunShooter",
  "ShootingCubes",
  "FlyPass",
  "KillAllZombies",
  "AnipopLink",
  "PetsMatch",
  "CrazyBomb",
  "SaveThePets",
  "SoccerHero",
  "MagicDonuts",
  "DeathRun",
  "MiningMaster",
  "Transform",
  "DefenseTower",
  "TwistyRoad",
  "ZooBlast",
  "CrazyPortal",
  "MahjongLink3D",
  "MergeAndDefense",
  "PetRun",
  "SkyRunning3D",
  "FillTheGlass",
  "PipePuzzle",
  "SuperDefense",
  "BubblePop",
  "CandyHit",
  "BrainMaster",
  "AntRun",
  "BombingTime",
  "BlockMaze",
  "MagicPainter",
  "ColorSplash",
  "RollingAgent",
  "RushingRover",
];

export const FEATURED_GAMES = ["BoardTheTrain", "JumpSmash", "TrafficRun"];
