export const SITE_NAME = "SuperEasyGame";
export const SITE_URL = "https://www.supereasygame.com/";
export const API_URL = `https://uptapapi.uptap.com/h5Game/?type=GameList&platform=uptapgame0120&token=dXB0YXBnYW1l572R56uZ55So`;
export const GAME_PATH = `https://uptapapi.uptap.com/h5Game/?type=Game&platform=baxiang_main&appid=`;
export const ADS_ID = `ca-pub-9209477879340784`;
export const GA_ID = `UA-183890722-16`;

export const SELECTED = [
  "Knife",
  "JumpSmash",
  "CrazyMoto",
  "CrazyKart3D",
  "FireTheGun",
  "FeverRacing",
  "ColorBall3D",
  "CrazyKnife",
  "BoardTheTrain",
  "MrRacer",
  "BigSword",
  "HiTaxi",
  "TrafficRun",
  "MrBullet",
  "LetMeIn",
  "SnakeGo",
  "DessertConnect",
  "SwiftRider",
  "CrackShot",
  "CrazyGunfight",
  "GoldenGlove",
  "ColorRing",
  "PianoKeys",
  "ArchersKing",
  "MyBabyCare",
  "DartsKing3D",
  "CrazyRace",
  "BallIsComing",
  "HungyBunny",
  "TheSameWorld",
  "SuperMiner",
  "BounceShooter",
  "HillRacing",
  "BatterKing",
  "BlockGun3D",
  "ZombieSurvival",
  "FruitMonster",
  "FierceCity",
  "IronAttack",
  "AceMan",
  "AirBrawl",
  "BumbleShooter",
  "AmazingRoad",
  "RainbowSplash",
  "MagicParkour",
  "CrazyDrift",
  "FisherMan",
  "FruitsFall",
  "RocketJump",
  "MagicPaint",
  "GlidingCharger",
  "RoadCharger",
  "ArcheryMaster",
  "UltraDrift",
  "SharkisComing",
  "PuppyRun",
  "PenguinDash",
  "MonsterCrash",
  "DeathJump",
  "HungryMonster",
  "HungryAnimals",
  "JumpingMonkey",
  "MergeKill",
  "CrazyTrain3D",
  "CrazyHammer",
  "VirusWar",
  "TrappedPirate",
  "StickmanVsZombies",
  "FingerCannon",
  "BulletMan",
  "KnockBalls",
  "GunShooter",
  "MergeGuns3D",
  "BulletMaster3D",
  "CrashTower3D",
  "TowerBlast3D",
  "ShootSmash",
  "ShootingCubes",
];
export const LATEST = [
  // "FruitsFal",
  // "RocketJump",
  // "MagicPaint",
  // "GlidingCharger",
  // "RoadCharger",
  // "ArcheryMaster",
];
export const FEATURED = ["CrazyMoto", "FireTheGun", "FeverRacing"];
